Parser help searching
SCIInstitute/SCIRun pull request #2170
Opened 2020-09-04 19:52 UTC by nids2001

Make parser help dialog searchable

2020-09-11 20:32 UTC, dcwhite commented
@nids2001 Build error: 
```/Users/runner/work/SCIRun/SCIRun/src/Interface/Modules/Base/HasParserHelpDialog.cc:73:3: error: use of undeclared identifier 'prevResult'
  prevResult = false;
  ^
1 error generated.```

2020-09-14 19:19 UTC, dcwhite commented
Will close #1534

2020-09-14 19:21 UTC, dcwhite requested changes

2020-09-14 19:21 UTC, dcwhite commented on src/Interface/Modules/Base/HasParserHelpDialog.cc
> +  help_ = new ParserHelpDialog(this);
This line (creating a new instance every time) leads to multiple dialogs being created each time the user clicks the show button. If you add back the null check, that will take care of only creating and showing one instance per module.

2020-09-17 22:27 UTC, dcwhite approved these changes

2020-09-17 22:29 UTC, dcwhite commented
👍

2020-09-18 20:08 UTC, jessdtate approved these changes

2020-09-18 20:10 UTC, merged