BBox Percentage Scaling for Point Probes
SCIInstitute/SCIRun pull request #2267
Opened 2021-04-24 04:04 UTC by RubioJr9

Issue: #1524
Reviewers: @jessdtate @dcwhite

-Added setting to scale sphere widgets as percentage of bounding box for:
    - GenerateSinglePointProbeFromField
    - GeneratePointSamplesFromField

- Fixed the tab ordering of UI elements in GSPPFF. Tab ordering is the order of UI elements when you hit the tab button.

2021-05-03 02:40 UTC, jessdtate approved these changes

2021-05-03 21:44 UTC, dcwhite requested changes
Problems:
- [ ] If no input field, the point probe disappears (probably because bbox is invalid or zero size)--should be an error, or default back to absolute size
- [ ] The two size widgets (percentage and absolute) should enable/disable with the checkbox toggle
- [ ] The percentage double spinbox ought to be 0-100 based (still floating point though, if someone wants 40.5%

2021-05-12 16:53 UTC, RubioJr9 commented
> Problems:
> 
>     * [ ]  If no input field, the point probe disappears (probably because bbox is invalid or zero size)--should be an error, or default back to absolute size
> 
>     * [ ]  The two size widgets (percentage and absolute) should enable/disable with the checkbox toggle
> 
>     * [ ]  The percentage double spinbox ought to be 0-100 based (still floating point though, if someone wants 40.5%)
> 
>     * [ ]  On mac, the new widgets are a bit smushed and need more space

I addressed all of these in the new commit

2021-05-18 00:47 UTC, dcwhite approved these changes

2021-05-18 18:29 UTC, allywarner approved these changes

2021-05-21 20:16 UTC, jessdtate approved these changes

2021-05-22 00:25 UTC, merged