Sizing Fix for EditMeshBoundingBox
SCIInstitute/SCIRun pull request #2283
Opened 2021-05-25 21:41 UTC by RubioJr9

The sizing in the menu for EditMeshBoundingBox is half of what it actually should be. For example, if a latvol goes from (-1,-1,-1) to (1,1,1), the current size is listed as 1 for each axis, when it actually should be 2. This was originally set to half because that is the distance from the center of the volume and that is what is used for constructing the transform matrix.

2021-05-26 17:06 UTC, dcwhite requested changes
All magic numbers. 

Define one constant that explains the issue, then either multiply or divide by it at the places you changed. So either `const double WIDGET_SCALE_FACTOR = 0.5` or `const double NORM_SCALE_FACTOR = 2.0`, your pick.

2021-05-26 17:13 UTC, RubioJr9 commented
Fair point. I'll update it today.

2021-05-28 22:39 UTC, jessdtate approved these changes

2021-06-03 17:14 UTC, dcwhite approved these changes

2021-06-03 17:14 UTC, merged