Show Glyphs Normals
SCIInstitute/SCIRun pull request #2320
Opened 2021-08-13 17:58 UTC by RubioJr9

This is a debugging tool for glyph normals. To show normals, I had to refactor the glyph constructor class. I extracted the private data members to a struct such that points, lines, and triangles had their data isolated. 

I added 2 new state variables to ShowFieldGlyphs:
ShowNormals(bool)
ShowNormalsScale(double)
Since this is a debugging tool, I didn't make a button for it. You have to set through the python api.

2021-08-13 20:36 UTC, dcwhite requested changes
first wave of line-level review

2021-08-13 20:36 UTC, dcwhite commented on src/Graphics/Glyphs/GlyphConstructor.cc
> +bool GlyphConstructor::normalsValid(SpireIBO::PRIMITIVE prim)
```suggestion
bool GlyphConstructor::normalsValid(SpireIBO::PRIMITIVE prim) const
```

2021-08-13 20:36 UTC, dcwhite commented on src/Graphics/Glyphs/GlyphConstructor.cc
> +  auto& data = getData(prim);
```suggestion
 const auto& data = getData(prim);
```

2021-08-13 20:36 UTC, dcwhite commented on src/Graphics/Glyphs/GlyphConstructor.cc
> +size_t GlyphConstructor::getCurrentIndex(SpireIBO::PRIMITIVE prim)
```suggestion
size_t GlyphConstructor::getCurrentIndex(SpireIBO::PRIMITIVE prim) const
```

2021-08-13 20:36 UTC, dcwhite commented on src/Graphics/Glyphs/GlyphConstructor.cc
> +  auto& data = getData(prim);
```suggestion
 const auto& data = getData(prim);
```

2021-08-13 20:36 UTC, dcwhite commented on src/Graphics/Glyphs/GlyphConstructor.h
> +struct GlyphData
```suggestion
struct SCISHARE GlyphData
```

2021-12-17 21:40 UTC, jessdtate approved these changes

2022-01-21 20:53 UTC, dcwhite approved these changes

2022-01-21 21:32 UTC, merged