Fix for Holes in Superquadric Tensor Glyphs
SCIInstitute/SCIRun pull request #2363
Opened 2022-01-10 20:17 UTC by RubioJr9

This fixes the small holes in the superquadric glyphs. This bug was because the round off was removed. I introduced it in PR #2264. This just reverts that change.

2022-01-21 20:54 UTC, dcwhite requested changes

2022-01-21 20:54 UTC, dcwhite commented on src/Graphics/Glyphs/GlyphGeomUtility.h
> +  const auto EPSILON = 1.0e-6;
```suggestion
  static const auto EPSILON = 1.0e-6;
```

2022-02-04 21:35 UTC, jessdtate approved these changes

2022-02-07 20:55 UTC, dcwhite approved these changes

2022-02-07 20:55 UTC, merged