Update ViewScene screenshot gui
SCIInstitute/SCIRun pull request #2368
Opened 2022-01-28 20:28 UTC by nids2001

- Keeps only one screenshot button in controls dock
- When button clicked, takes a quick screenshot 
- New Gui
  - Save Screenshot As button
  - Set Default Directory for quick screenshots
    - Saves directory to module state

2022-03-31 15:33 UTC, dcwhite requested changes
New GUI looks great! Just a couple small tweaks requested

2022-03-31 15:33 UTC, dcwhite commented on src/Interface/Modules/Render/ViewScene.cc
> +         QString("/%1_%2.png").arg(QString::fromStdString(getName()).replace(':', '-')).arg(QTime::currentTime().toString("hh.mm.ss.zzz"));
```suggestion
         QString("/%1_%2.png").arg(QString::fromStdString(getName()).replace(':', '-')).arg(QDateTime::currentDateTime().toString("yyyy.MM.dd.HHmmss.zzz"));
```

2022-03-31 15:33 UTC, dcwhite commented on src/Interface/Modules/Render/ViewScene.cc
> +         QString("/%1_%2.png").arg(QString::fromStdString(getName()).replace(':', '-')).arg(QTime::currentTime().toString("hh.mm.ss.zzz"));
Not sure why we lost the date there, just the time is not as useful.

2022-04-11 19:36 UTC, jessdtate approved these changes

2022-04-12 19:34 UTC, dcwhite approved these changes

2022-04-12 19:34 UTC, merged