Classic Tutorial
SCIInstitute/SCIRun pull request #2411
Opened 2022-11-29 17:30 UTC by nids2001

Ports BIOPSE classic tutorial ([http://scirundocwiki.sci.utah.edu/SCIRunDocs/index.php/CIBC:Documentation:SCIRun:Tutorial:BioPSE:Chapter_1](http://scirundocwiki.sci.utah.edu/SCIRunDocs/index.php/CIBC:Documentation:SCIRun:Tutorial:BioPSE:Chapter_1)) to markdown as mentioned in #1156

2023-01-17 18:24 UTC, dcwhite submitted a review, later dismissed

2023-01-19 22:38 UTC, jessdtate requested changes

2023-01-19 22:38 UTC, jessdtate commented on docs/user_doc/ClassicTutorial.md
> +-TODO: update show-torso-mesh.srn to SR5 and add to example nets
@nids2001 did you update this example network?

2023-01-27 19:14 UTC, jessdtate requested changes

2023-01-27 19:14 UTC, jessdtate commented on docs/user_doc/ClassicTutorial.md
> +2. Position the mouse pointer over the yellow output port on the **ReadField**. Press and hold the right mouse button. The name of the port and lines indicating possible data pipe connections will ap
left mouse button.

2023-01-27 19:14 UTC, jessdtate commented on docs/user_doc/ClassicTutorial.md
> +3. Continue to hold the right middle button and drag the mouse toward the first yellow **ShowField** input port.
left mouse buttion

2023-01-27 19:14 UTC, jessdtate commented on docs/user_doc/ClassicTutorial.md
> +4. The line turns gray, showing the desired connection has been selected. See ({numref}`fig-pipe-selection`).
turns red

2023-01-27 19:14 UTC, jessdtate commented on docs/user_doc/ClassicTutorial.md
> +## Dynamic Commpilation
this isn't supported anymore, so this section should be removed

2023-01-27 19:14 UTC, jessdtate commented on docs/user_doc/ClassicTutorial.md
> +1. Select the UI button on the **ShowField** module.
reference fig-module-info

2023-01-27 19:14 UTC, jessdtate commented on docs/user_doc/ClassicTutorial.md
> +## Mouse Controls
these are the old controls

2023-02-01 19:20 UTC, jessdtate approved these changes

2023-02-03 18:06 UTC, dcwhite approved these changes

2023-02-06 20:49 UTC, merged